config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  get 'profile',                  to: 'users#show',  as: 'user'
  get 'dashboard',                to: 'admin#index'
  get 'login',                    to: 'sessions#new'
  post 'login',                   to: 'sessions#create'
  delete 'logout',                to: 'sessions#destroy'
  get 'my_albums',                to: 'my_albums#index'
  get 'album/comments/delete',    to: 'comments#destroy'
  get 'admin/albums/delete',      to: 'admin/albums#destroy'
  get 'admin/users/delete',       to: 'admin/users#destroy'
  get 'album/download',           to: 'album/download#index'


  namespace :api do
    namespace :v1 do
      resources :albums, only: [:show] do
        resources :comments, except: [:edit, :new]
      end
    end
  end

  resources :users, only: [:new, :create, :update, :edit]
  resources :user_profiles, only: [:edit, :update]
  resources :confirmations, only: [:new, :create]
  resources :albums do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :photos, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :album_users, only: [:new, :create]

  namespace :admin do
    resources :albums, only: [:index]
    resources :users, only: [:index, :edit, :show, :update]
  end
end

app/views/admin/index.html.erb
<div class="container">
  <h3>Admin Dashboard</h3>
  <div class="col-md-8 well">
    <div class="container">
      <%= render 'shared/user_show', user: @user %>
      <div class="btn-group col-md-offset-1">
        <%= link_to "All Albums", admin_albums_path, class: "btn btn-default btn" %>
        <%= link_to "All Users", admin_users_path, class: "btn btn-default btn" %>
      </div>
    </div>
  </div>
</div>