config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  get 'profile',                  to: 'users#show',  as: 'user'
  get 'dashboard',                to: 'admin#index'
  get 'login',                    to: 'sessions#new'
  post 'login',                   to: 'sessions#create'
  delete 'logout',                to: 'sessions#destroy'
  get 'my_albums',                to: 'my_albums#index'
  get 'album/comments/delete',    to: 'comments#destroy'
  get 'admin/albums/delete',      to: 'admin/albums#destroy'
  get 'admin/users/delete',       to: 'admin/users#destroy'
  get 'album/download',           to: 'album/download#index'


  namespace :api do
    namespace :v1 do
      resources :albums, only: [:show] do
        resources :comments, except: [:edit, :new]
      end
    end
  end

  resources :users, only: [:new, :create, :update, :edit]
  resources :user_profiles, only: [:edit, :update]
  resources :confirmations, only: [:new, :create]
  resources :albums do
    resources :comments, only: [:create, :destroy, :edit, :update]
  end
  resources :photos, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :album_users, only: [:new, :create]

  namespace :admin do
    resources :albums, only: [:index]
    resources :users, only: [:index, :edit, :show, :update]
  end
end

app/views/shared/_album_form.html.erb
<div class="col-md-6 col-md-offset-3 text-center">
  <h3><%= header %> Album</h3>
    <%= form_for album do |f| %>
      <div class="form-group text-left">
        <%= f.label :title %>
        <%= f.text_field :title, value: album.title, class: "form-control" %>
      </div>

      <div class="form-group text-left">
        <%= f.label :description %>
        <%= f.text_area :description, value: album.description, class: "form-control" %>
      </div>

      <%= f.check_box :public, :data => { :size => 'large', 'on-text' => 'Public', 'off-text' => 'Private'} %>

      <div class=btn-group>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#album_public').bootstrapSwitch('state', <%= album.public %>)
  });
</script>

app/views/shared/_album_tiles.html.erb
<div class="albums container">
  <% if !albums.empty? %>
    <h3><%= context %> Albums</h3>
    <% albums.each do |album| %>
      <div class="container col-md-3">
        <div class="photo_tile well">
          <%= link_to album.title, album_path(album) %>
          <% photo = album.photos.first %>
          <% if photo %>
            <div class="thumbnail">
              <%= image_tag photo.image %>
            </div>
            <%= album.description.truncate_words(4) %></br>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_create_album_link.html.erb
<li role="presentation">
  <%= link_to "Create Album", new_album_path, class: "nav-item nav-link navbar-right" %>
</li>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, class: "alert alert-#{type}" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= sanitize(msg) %>
  <% end %>
<% end %>

app/views/shared/_logout_link.html.erb
<li role="presentation">
  <%= link_to "Logout", logout_path, method: :delete %>
</li>

app/views/shared/_my_albums_link.html.erb
<li role="presentation"><%= link_to "My Albums", '/my_albums', class: "nav-item nav-link navbar-right" %></li>

app/views/shared/_navigation.html.erb
<div class="nabbar-default">
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to "Turing Photoshare", root_path, class: "navbar-nav-item nav-link" %></li>
    <% if guest_user? %>
      <%= render 'shared/navigation_guest' %>
    <% elsif admin_user? %>
      <%= render 'shared/navigation_admin' %>
    <% elsif current_user %>
      <%= render 'shared/navigation_logged_in' %>
    <% end %>
  </ul>
</div>

app/views/shared/_navigation_admin.html.erb
<%= render 'shared/my_albums_link' %>
<%= render 'shared/create_album_link' %>
<li role="presentation"><%= link_to "Admin dashboard", dashboard_path, class: "nav-item nav-link navbar-right" %></li>
<%= render 'shared/profile_link' %>
<%= render 'shared/logout_link' %>

app/views/shared/_navigation_guest.html.erb
<li role="presentation"><%= link_to "Login", login_path, class: "nav-item nav-link navbar-right" %></li>
<li role="presentation"><%= link_to "Create Account", new_user_path, class: "nav-item nav-link navbar-right" %></li>

app/views/shared/_navigation_logged_in.html.erb
<%= render 'shared/my_albums_link' %>
<%= render 'shared/profile_link' %>
<%= render 'shared/create_album_link' %>
<%= render 'shared/logout_link' %>

app/views/shared/_photo_tile.html.erb
<div class="container col-md-3">
  <div class="photo_tile well">
    <% if photo %>
      <div class="thumbnail">
        <%= image_tag photo.image %>
      </div>
      <%= photo.caption %></br>
      <% if @album.owner?(current_user) %>
        <%= link_to 'Delete photo', photo_path(photo), method: :delete %></br>
        <%= link_to 'Edit caption', edit_photo_path(photo) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_profile_link.html.erb
<li role="presentation"><%= link_to "Profile", '/profile', class: "nav-item nav-link navbar-right" %></li>

app/views/shared/_user_profile_row.html.erb
<tr>
  <th> <%= key %>: </th>
  <td> <%= value %> </td>
</tr>

app/views/shared/_user_show.html.erb
<h3><%= user.username %></h3>
<% if user.inactive? %>
  <h4 class="small">Status: <%= user.status %></h4>
<% end %>
<h5>Profile info:</h5>
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <%= render 'shared/user_profile_row', key: "Email", value: user.user_profile.email %>
      <%= render 'shared/user_profile_row', key: "Phone", value: user.phone_number %>
      <%= render 'shared/user_profile_row', key: "Bio", value: user.user_profile.bio %>
    </table>
  </div>
</div>

<div class="row btn-group">
  <%= link_to "Edit profile", edit_user_profile_path(user.user_profile), class: "btn btn-default" %>
  <%= link_to "Generate API Token", "/users/#{user.id}", method: :patch, class: "btn btn-default" %>
</div>